from enum import Enum

class WordTags(Enum):
    NOUN = ['NN', 'NNS', 'NNP', 'NNPS']
    PRONOUN = ['PRP', 'PRP$']
    ADJECTIVE = ['JJ', 'JJR', 'JJS']
    VERB = ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']
    ADVERB = ['RB', 'RBR', 'RBS']
    CONJUNCTION = ['CC']
    PREPOSITION = ['IN']
    INTERJECTION = ['UH']
    DETERMINER = ['DT']
    MODAL = ['MD']
    POSSESSIVE = ['POS']
    WH_WORD = ['WDT', 'WP', 'WP$', 'WRB']
    NUMERAL = ['CD']
    PARTICLE = ['RP']
    SYMBOL = ['SYM']
    TO = ['TO']
    ARTICLE = ['DT', 'IN']
    CARDINAL = ['CD']
    FOREIGN_WORD = ['FW']
    LIST_MARKER = ['LS']
    O = ['O']
